### ISSUE TITLE
List of TODO's

### ISSUE THREAD

**Issue by mkonecny** [davidbalbert/eventless#3]
Would love to see a list of TODO's required to complete this project. What are the current show-stoppers, what needs improvement etc. I think this project would a be a great addition to the ruby community, and implementing this TODO might inspire some developers to contribute.

Here's a similar list created by the Rust community: http://www.reddit.com/r/rust/comments/2j37om/the_great_big_libcollections_todo_list/

**Comment by davidbalbert** [comment]
@mkonecny I no longer think the direction I was going down with Eventless is a good idea. Eventless would only ever be able to work with libraries written in pure Ruby. There are enough critical libraries that are written in C and do I/O that I think Eventless would be effectively useless. Furthermore, if you happen to use any of those gems with Eventless, your event loop will get blocked with no warning.

Thanks for your interest though!
